spring.application.name=mapa-hexa
app.cors.allowed-origins=http://localhost:5173
spring.config.import=optional:classpath:application-local.properties

# JWT Configuration
jwt.secret=sua-chave-secreta-muito-longa-e-segura-aqui-coloque-uma-string-bem-comprida-minimo-256-bits
jwt.expiration=86400000
